services:
  server:
    image: drupal:latest # this will use the latest version of 1.23
    ports:
      # NOTE: if port 80 is already in use on your host, this won't work
      # in that case, change to any high port, like '8000:80'
      # and then use http://localhost:8000 to access the proxy
      - '8080:80' # 
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  db:
    image: postgres:latest  # this will use the latest apache v2
    environment:
      POSTGRES_PASSWORD: example

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: